"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
command_timeout = 1000
format = """
 âœ\
$directory\
${custom.giturl}\
$git_branch\
$git_state\
$git_status\
$line_break\
$character
"""
palette = "catppuccin_mocha"
right_format = """$all"""

[c]
format = '[[ $symbol( $version) ]]($style)'
symbol = "î˜ "

[character]
disabled = false
error_symbol = '[ğ˜¹](bold fg:red)'
success_symbol = '[ğ˜¹](bold fg:green)'
vimcmd_replace_one_symbol = '[ï´](bold fg:purple)'
vimcmd_replace_symbol = '[ï´](bold fg:purple)'
vimcmd_symbol = '[ï´](bold fg:creen)'
vimcmd_visual_symbol = '[ï´](bold fg:lavender)'

[custom.giturl]
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL="ïˆ "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL="ïŠ– "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL="ï…± "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL="ï¡ "
else
    GIT_REMOTE_SYMBOL="ï‡’ "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
# disabled = true
description = "Display symbol for remote Git server"
format = "at $output"
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'

[directory]
format = "[ $path ]($style)"
style = "sapphire"

[directory.substitutions]
"Developer" = "ó°²‹ "
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "

[docker_context]
format = '[ $symbol( $context) ]($style)'
symbol = "ïŒˆ"

[git_branch]
format = '  on [$symbol$branch]($style)[î‚´](black)'
# format =  ' [$symbol$branch(:$remote_branch)]($style)[î‚´]'
style = "fg:lavender bg:black"
symbol = "[î‚¶](black)ï˜ "

[git_status]
format = ' [($all_status$ahead_behind )]($style)'

[golang]
detect_files = ["go.mod"]
format = '[ $symbol( $version) ]($style)'
symbol = "î˜§"

[haskell]
format = '[[ $symbol( $version) ]]($style)'
symbol = "î˜Ÿ"

[java]
format = '[[ $symbol( $version) ]]($style)'
symbol = "î‰– "

[kotlin]
format = '[[ $symbol( $version) ]]($style)'
symbol = "î˜´"

[line_break]
disabled = true

[nodejs]
format = '[ $symbol( $version) ]($style)'
symbol = "îœ˜"

[os]
disabled = true

[os.symbols]
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
Fedora = "ó°£›"
Gentoo = "ó°£¨"
Linux = "ó°Œ½"
Macos = " îœ‘"
Manjaro = "ïŒ’"
Mint = "ó°£­"
Raspbian = "ó°¿"
RedHatEnterprise = "ó±„›"
Redhat = "ó±„›"
SUSE = "ïŒ”"
Ubuntu = "ó°•ˆ"
Windows = "ó°²"

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[php]
format = '[[ $symbol( $version) ]]($style)'
symbol = "î˜ˆ"

[python]
format = '[[ $symbol( $version) ]]($style)'
symbol = "î˜†"

[rust]
format = '[[ $symbol( $version) ]]($style)'
symbol = "î¨"

[time]
disabled = true
format = '[[ ïº $time ](fg:mantle bg:foam)]($style)'
style = "bg:peach"
time_format = "%R"

[username]
